### ISSUE TITLE
DescriptionLine doesn't show amount in quickbooks on invoice

### ISSUE THREAD

**Issue by sabrarossman** [sidecars/python-quickbooks#101]
I am trying to add a description line to my invoice and the amount is not showing up when I look at it in quickbooks.  Description looks fine, but no $ amount.  I can add the amount in quickbooks to that line so I don't understand what is wrong.
            line = DescriptionLine()
            line.LineNum = lineNum
            line.Description = lineitem.description
            line.Amount = 100
            line.DescriptionLineDetail = DescriptionLineDetail()
            line.DescriptionLineDetail.ServiceDate = service_date
            invoice.Line.append(line)

**Comment by ej2** [comment]
@sabrarossman did you ever get this issue resolved?

**Comment by b4thestorm** [comment]
Hi guys, 

I believe that intuit is calculating the amount from the  payload that the client is generating. So this code is missing what Intuit would consider to be a calculable amount. 

The correct sequence of building the LineItem is with a node for:
```python 
line.SalesItemLineDetail` = SalesItemLineDetail()
line.SalesItemLineDetail.UnitPrice = 100
```
This code will include the UnitPrice and this should create a new invoice for you:

```python
invoice = Invoice()
line = SalesItemLine()
line.LineNum = 1
line.Description = 'description here'
line.Amount = 100

line.SalesItemLineDetail = SalesItemLineDetail()
line.SalesItemLineDetail.Qty = 1
line.SalesItemLineDetail.UnitPrice = 100
line.SalesItemLineDetail.ItemRef = line_item.to_ref()

invoice.Line.append(line)
invoice.CustomerRef = customer.to_ref()
invoice.save(qb=qbclient)
return invoice.Id
