### ISSUE TITLE
Sandbox parameter to Quickbooks and OAuthXSessionManager

### ISSUE THREAD

**Issue by jonovate** [sidecars/python-quickbooks#102]
Is there a reason both the ```QuickBooks``` object and the ```OAuth1SessionManager``` / ```OAuth2SessionManager``` require **sandbox**?

**Comment by ej2** [comment]
Nope... Sandbox is used on the Quickbooks object but not in OAuth1SessionManager/OAuth2SessionManager. I will work on removing it from the Session Managers.

**Comment by jonovate** [comment]
That's what I was thinking - smelt like a refactor.

Also - the README.md showing how to use Minor Version was missed on your last major update.
