### ISSUE TITLE
Missing country in the address object

### ISSUE THREAD

**Issue by porn** [sidecars/python-quickbooks#11]
Hey,

I'm a bit confused but it seems that the [Address object](https://github.com/sidecars/python-quickbooks/blob/b24ecd79fc4216b7843884a440487f8588dab0fd/quickbooks/objects/base.py#L50) is missing the [country attribute](https://developer.intuit.com/docs/95_legacy/qbd_v2/qbd_v2_reference/062_enumerations/physicaladdress)?

Or is there another way how to provide it e.g. when creating a [new customer](https://developer.intuit.com/docs/api/accounting/customer)?

**Comment by ej2** [comment]
I will look into it.

**Comment by ej2** [comment]
Added Country and other missing fields to Address. FYI: the documentation you linked to is not valid for QBO V3.

**Comment by porn** [comment]
Great! Thanks for the quick reply/action :beers:
