### ISSUE TITLE
How to access the details of BillAddr within a Customer object?

### ISSUE THREAD

**Issue by johnnydisco** [sidecars/python-quickbooks#113]
Can I access Line1 etc from within the BillAddr?  I only seem to have BillAddr as a whole.

Thanks

"Customer": {
        "Taxable": false,
        "BillAddr": {
            "Id": "3",
            "Line1": "12 Ocean Dr.",
            "City": "Half Moon Bay",
            "CountrySubDivisionCode": "CA",
            "PostalCode": "94213",
            "Lat": "37.4307072",
            "Long": "-122.4295234"
        }

**Comment by johnnydisco** [comment]
Anyone?  I can't get any of the details within the object...

**Comment by ej2** [comment]
BillAddr should be an Address object (defined [here](https://github.com/sidecars/python-quickbooks/blob/master/quickbooks/objects/base.py)).  So you should be able to access Line1 like so: 
`line1 = customer.BillAddr.Line1`

Note:  Objects and object property names match their Quickbooks counterparts and do not follow PEP8.
