### ISSUE TITLE
Flask App - quickbooks.exceptions.AuthorizationException

### ISSUE THREAD

**Issue by johnnydisco** [sidecars/python-quickbooks#118]
I'm having problems with a Flask app.  The auth flow works fine and I save the token in a database fine, I can then query the API and correctly get customer lists, invoices etc from QBO.  The token is being renewed correctly and resaved in the database BUT if I leave the app until after the token will have expired I get the following error.

> quickbooks.exceptions.AuthorizationException
> quickbooks.exceptions.AuthorizationException: QB Auth Exception: Application authentication failed 
> 
> {"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthenticationFailed; errorCode=003200; statusCode=401","detail":null,"code":"3200","element":null}],"type":"AUTHENTICATION"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1533811101733,"status":null,"cdcresponse":[]}

There doesn't seem to be a problem with the refresh because if I restart the app, the token refreshes correctly and I get my customer list.  Does something else time out or could it be the session_manager = Oauth2SessionManager be in the route rather than at the beginning?  I cannot work out what's wrong.

**Comment by ej2** [comment]
@johnnydisco are you still having an issue with this?

**Comment by E-G-C** [comment]
@ej2 I would suggest to close it one out as OP hasn't followed up on this.

**Comment by trungdiep** [comment]
Hi @E-G-C. i get this error.
quickbooks.exceptions.AuthorizationException: QB Auth Exception 401: Application authentication failed
{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthenticationFailed; errorCode=003200; statusCode=401","detail":null,"code":"3200","element":null}],"type":"AUTHENTICATION"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1698893034260,"status":null,"cdcresponse":[]}.

**Comment by ej2** [comment]
@trungdiep is this related to the original issue?
