### ISSUE TITLE
Application authentication failed, code 100

### ISSUE THREAD

**Issue by Filip-Duc** [sidecars/python-quickbooks#120]
Hello, our app just stopped working. Everything was working fine and suddenly we get error code 100 everywhere. We are using the sandbox. The app was authorized just before testing.

Full error:
QB Auth Exception: Application authentication failed 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2018-08-20T02:23:36.095-07:00"><Fault type="AuthenticationFault"><Error code="100"><Message>General Authentication Error</Message><Detail>AuthenticationErrorGeneral: SRV-110-Authentication Failure , statusCode: 401</Detail></Error></Fault></IntuitResponse>

The access token received from QB looks weird (two dots next to each other? Does it look normal?):
Bearer eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..bHBkGn5MH32cMyV1148p5A. (...rest of the access token)

Any tips?

**Comment by mshvern** [comment]
The access token is only active for one hour, you have to refresh it.

**Comment by ej2** [comment]
You can call `session_manager.refresh_access_token()` to refresh your access token (added to version 0.7.5). See the documentation for details.
