### ISSUE TITLE
Uploading Attachable object to vendor error code 5010

### ISSUE THREAD

**Issue by aorfanos1** [sidecars/python-quickbooks#127]
Hi - When I try to create a vendor and then create an attachable, or in certain instances when I am tryin g to access an attachable on a vendor I am getting the error back from the quickbooks api -
`[{'Message': 'Stale Object Error', 'Detail': 'Stale Object Error : You and API API were working on this at the same time. API API finished before you did, so your work was not saved.', 'code': '5010', 'element': ''}]` -
and so I subsequently get an error from the sdk. Do you know how to prevent this error or is this an issue with the sdk?

**Comment by ej2** [comment]
I have not encountered this error before.  [This thread](https://help.developer.intuit.com/s/question/0D50f00004n4DmOCAU/stale-object-error-5010-why-how-to-refresh) suggests incrementing the sync token. You could do that like so: 
`vendor.SyncToken = 1`
