### ISSUE TITLE
No Preferences object

### ISSUE THREAD

**Issue by justmobilize** [sidecars/python-quickbooks#129]
I am needing the `Preferences` object, but it's not yet built out. Do you have plans to do this?

**Comment by ej2** [comment]
I have no plans currently to implement the Preferences object. Feel free to built it and submit a PR.

**Comment by justmobilize** [comment]
Thanks. If I have time, I will. I may just do a raw get. If other people want it, I'll make time

**Comment by thismatters** [comment]
It would be nice to have this.
