### ISSUE TITLE
ItemBasedExpenseLineDetail.BillableStatus set to empty string on __init__

### ISSUE THREAD

**Issue by justmobilize** [sidecars/python-quickbooks#133]
https://github.com/sidecars/python-quickbooks/blob/4cb2b6da46423bad8b32b85d87f9a97b698144fd/quickbooks/objects/detailline.py#L223

Is there a reason `ItemBasedExpenseLineDetail.BillableStatus` is set to empty string on `__init__`?

It is not a required field and populating a Bill from an object that doesn't have this field can not be created since empty string is not a valid value

**Comment by ej2** [comment]
Resolved in 0.8 release.
