### ISSUE TITLE
Refreshing tokens?

### ISSUE THREAD

**Issue by ckcollab** [sidecars/python-quickbooks#134]
Hey there, thanks so much for the great work on this! It has been a relative dream to connect our small app with Quickbooks, appreciate it.

Apologies if this is already documented somewhere, but one small misunderstanding we're having is how we should be refreshing upon connection to QuickBooks. 

```python
session_manager = Oauth2SessionManager(
    client_id=QUICKBOOKS_CLIENT_ID,
    client_secret=QUICKBOOKS_CLIENT_SECRET,
    base_url=callback_url, # the base_url has to be the same as the one used in authorization
)

# caution! invalid requests return {"error":"invalid_grant"} quietly
session_manager.get_access_tokens(request.GET['code'])
access_token = session_manager.access_token
refresh_token = session_manager.refresh_token
```

So we do this and have a connection, how often should we be refreshing the token? We've been using a method like this to ensure it should be fresh each time, but it gets some strange behavior (the first signon after a while fails to connect properly)

```python
def get_qb_client():
    from .models import User

    master_user = User.objects.get(qb_master_user=True)

    session_manager = Oauth2SessionManager(
        client_id=settings.QUICKBOOKS_CLIENT_ID,
        client_secret=settings.QUICKBOOKS_CLIENT_SECRET,
        access_token=master_user.qb_access_token,
        refresh_token=master_user.qb_refresh_token,
    )

    session_manager.start_session()
    session_manager.refresh_access_tokens()

    master_user.qb_access_token = session_manager.access_token
    master_user.qb_refresh_token = session_manager.refresh_token
    master_user.save()

    return QuickBooks(
        sandbox=True,
        session_manager=session_manager,
        consumer_key=settings.QUICKBOOKS_CLIENT_ID,
        consumer_secret=settings.QUICKBOOKS_CLIENT_SECRET,
        company_id=settings.QUICKBOOKS_COMPANY_ID,
    )
```

We're probably using it a bit wrong, any advice would be appreciated!

**Comment by E-G-C** [comment]
@ckcollab 
                      An access token expires in an hour. For example,  in my implementation,  I check in case it needs to be refreshed before sending a request something like this: 
```
        token_age = datetime.datetime.utcnow() - result.payload[0]['token_last_refreshed']
        # adding a buffer time of 60 seconds to avoid sending a request when the token is about to expire
        buffer_time = datetime.timedelta(seconds=60)
        if (token_age + buffer_time).seconds > datetime.timedelta(
                seconds=result.payload[0]['access_token_exp']).seconds:
               logger.info('Token expired,  calling to refresh token')

```
I guess my only advise would be to make sure you are indeed getting a new token when you call to refresh_token

For more info about the topic see:
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#understand-token-expiration

**Comment by ej2** [comment]
No longer relevant since OAuth Session Manager has been removed.
