### ISSUE TITLE
Change behaviour of session_manager.get_access_tokens

### ISSUE THREAD

**Issue by aymericderbois** [sidecars/python-quickbooks#136]
Hello,

# Problem
When retrieving tokens, the `get_access_tokens` function with the `return_result` variable at `True` doesn't always return the same type.
When everything goes well, a `dict` is returned, and otherwise it is a `str`.

```python
session_manager = Oauth2SessionManager(
    client_id=QUICKBOOKS_CLIENT_ID,
    client_secret=QUICKBOOKS_CLIENT_SECRET,
    base_url=QUICKBOOKS_CALLBACK_URL,
)

result = session_manager.get_access_tokens(request.GET['code'], True)

# On success :
type(result)  # dict

# On error :
type(result)  # str
```

# Proposal

My proposal is to return a tuple, with as first value the content (with `str` type) of the request response, and as second value a boolean to know if the request has failed or not.

```python
session_manager = Oauth2SessionManager(
    client_id=QUICKBOOKS_CLIENT_ID,
    client_secret=QUICKBOOKS_CLIENT_SECRET,
    base_url=QUICKBOOKS_CALLBACK_URL,
)

response, success = session_manager.get_access_tokens(request.GET['code'], True)
type(response)  # str
type(success)  # bool
```

# Conclusion

Does that seem like a logical idea to you?
I can do the development and PR if you want!

Thank you for reading me.
Aymeric,

**Comment by ej2** [comment]
No longer relevant since OAuth Session Manager has been removed.
