### ISSUE TITLE
Readme - Issue with refresh_access_tokens()

### ISSUE THREAD

**Issue by johnnydisco** [sidecars/python-quickbooks#137]
Only a small flag which may save someone time.  In the readme:

`session_manager.refresh_access_token()`

In the class it's:

`refresh_access_tokens`

Works fine if you refresh as:

`session_manager.refresh_access_tokens()`

**Comment by AguD** [comment]
Another related issue in the readme;
```
session_manager = Oauth2SessionManager(
       client_id=QUICKBOOKS_CLIENT_ID,
       client_secret=QUICKBOOKS_CLIENT_SECRET,
       base_url=callback_url,
   )

session_manager.refresh_access_token()
```
That's the code given to refresh access token, but actually you need something more like this
```
    session_manager = Oauth2SessionManager(
        client_id=settings.QUICKBOOKS_CLIENT_ID,
        client_secret=settings.QUICKBOOKS_CLIENT_SECRET,
        refresh_token=<Token you get previously when authenticating>
    )
```
And then you can call session_manage.refresh_access_tokens()

**Comment by chandeeland** [comment]
i opened a PR #138  for this

**Comment by ej2** [comment]
No longer relevant since OAuth Session Manager has been removed.
