### ISSUE TITLE
Exception when creating customer with parent

### ISSUE THREAD

**Issue by FinniMcFinger** [sidecars/python-quickbooks#139]
I am trying to create a sub-customer in QuickBooks, primarily in sandbox environment. My client's QB is set up such that each project is a sub-customer of the actual customer.

```python
try:
    project = Project.objects.get(pk=1)
    parent = my_qb_wrapper.get_cust_by_id(project.customer.qb_id)
    qb_cust = Customer()
    qb_cust.DisplayName = project.billing_name
    qb_cust.CompanyName = project.client.name
    qb_cust.ParentRef = parent.to_ref()
    qb_cust.BillWithParent = True
    qb_cust.Active = True
    qb_cust.save(qb=qb.client)
except Exception as exc:
    print(str(exc))
```

Exception prints as: `Unknown to QB: ParentRef Required Error`

I have confirmed the parent exists in QuickBooks. Am I missing something for associating a customer with a parent?

**Comment by goofygoblin** [comment]
Hi,

Just had this problem myself. You need to set Customer.Job = True when specifying a parent. I also set Customer.Level = 1, however not tested if this is required or played around with it as 1 level is all I need.

From the quickbook docs (https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/customer#the-customer-object);
**Customer.Job** - If true, this is a Job or sub-customer. If false or null, this is a top level customer, not a Job or sub-customer.
**Customer.Level** - Specifies the level of the hierarchy in which the entity is located. Zero specifies the top level of the hierarchy; anything above will be level with respect to the parent. Constraints:up to 5 levels
