### ISSUE TITLE
Add support for downloading PDFs

### ISSUE THREAD

**Issue by porn** [sidecars/python-quickbooks#14]
First of all, thank you for the great work, you've done so far with this library!

The [quickbooks API](https://developer.intuit.com/docs/api/accounting/Invoice) allows downloading PDF for some of the "TRANSACTION ENTITIES":
- Estimate
- Invoice
- SalesReceipt

I'm going to need this functionality, so I'll probably implement this. Any advice on where to place the code? Should I create a new class (say `QuickbooksPdfDownloadable`?) that will be extended by the listed classes and will require implementation of `get_pdf_api_url()` abstract method or something like that?

What should the tests look like? Are they required?

**Comment by ej2** [comment]
Sounds good. I would add QuickbooksPdfDownloadable to mixins.py. You might also create methods to get just the url or the actual file. Tests are required.

**Comment by Tusky** [comment]
support for uploading would be also great. :)
