### ISSUE TITLE
DocNumber key should be sent in the request body if not explicitly set

### ISSUE THREAD

**Issue by bendavis78** [sidecars/python-quickbooks#141]
Quickbooks automatically generates DocNumber on invoices if not supplied. However, when creating a new invoice using `Invoice.save()`, the DocNumber is set to an empty string, and Quickbooks assumes you want the DocNumber to be empty. 

If a key is not explicitly set, it should not be sent in the request body. Otherwise, there is no way to create an invoice and let QBO generate the DocNumber.

**Comment by justmobilize** [comment]
@bendavis78 in the time being, you can set it to `None` before saving which will cause it not to get sent up. It's set to an empty string on `init`

**Comment by ej2** [comment]
Resolved in 0.8 release.
