### ISSUE TITLE
Batch Create - How to match back to original request?

### ISSUE THREAD

**Issue by johnnydisco** [sidecars/python-quickbooks#143]
When a batch operation happens, Intuit says that you cannot guarantee the order in which the success or failure comes back from the API.

When I use the example code below, I can spit out all the ones which were successful and I know that the DisplayName in QBO has to be unique, fab!

What I don't understand is how you'd track 2 invoices to the same customer and therefore DisplayName?  Is there a unique ID for each success I can match back to the original request?

```
for obj in results.successes:
    print "Updated " + obj.DisplayName
```

**Comment by ej2** [comment]
@johnnydisco did you ever figure this out?

**Comment by johnnydisco** [comment]
No, have I missed something stupid?  I am currently stuck raising them as a single one.. could you point me in the right direction or is it just the case I need to check for duplicate DisplayNames and if that's the case not put through in a batch?

**Comment by ej2** [comment]
You should be able to use the Id field on the Invoice object. [Invoice Documentation](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice#the-invoice-object).

**Comment by johnnydisco** [comment]
Just so I understand you're saying generate a unique ID, maybe a UUID for each invoice, add each invoice to the batch and upload and the response from the API will return the unique ID I sent so rather than check the name, I check the IDs match.. If so you're a genius and I owe you a beer...

**Comment by ej2** [comment]
Yeah, you could put your unique Id in DocNumber or PrivateNote on the invoice. The API even has support for custom fields (Check out CustomField property on the Invoice).
