### ISSUE TITLE
Unable to create JournalEntry

### ISSUE THREAD

**Issue by gportly** [sidecars/python-quickbooks#144]
I am unable to create a JournalEntry and receive the "quickbooks.exceptions.QuickbooksException: Request has invalid or unsupported property" error when executing JournalEntry.save(qb=client). I have been unable to find a problem with the json request body despite multiple edits and iterations (I've tried many bodies :) ), but suspect that is where the issue is. The body is accepted by the Intuit Developer sandbox here: https://developer.intuit.com/v2/apiexplorer?apiname=v3qbo#?id=JournalEntry.

Using the QBO Python SDK I am able to successfully create estimates, customers, and invoices.

Code:

# CREATE QBO JOURNALENTRY OBJECT
from quickbooks.objects.journalentry import JournalEntry

journalentry = JournalEntry()
journalentry = journalentry.from_json({
  "Line": [
    {
      "Amount": 100.0,
      "DetailType": "JournalEntryLineDetail",
      "JournalEntryLineDetail": {
        "PostingType": "Debit",
        "AccountRef": {
                "value": "38"
              }
      }
    },
    {
      "Amount": 100.0,
      "DetailType": "JournalEntryLineDetail",
      "JournalEntryLineDetail": {
        "PostingType": "Credit",
        "AccountRef": {
                "value": "81"
              }
      }
    }
  ]
}
)

journalentry.save(qb=client)

**Comment by ej2** [comment]
@gportly are you still having an issue with this?
