### ISSUE TITLE
How to pass date filters when fetching?

### ISSUE THREAD

**Issue by zmcddn** [sidecars/python-quickbooks#147]
Hi, 

I wonder if I can fetch data with dates filtered. 
For example, I wanna fetch all the invoices in the past two years, not all the invoices, how can I do this?
Normally, I would do something like:
Invoices.all(qb=client, max_result=1000)

But I saw that there is "**kwargs" in the source code for filtering. I wonder what key word should I pass in for the date filter.
I wanna do something like:
Invoices.filter(qb=client, date__gt = (current_date - 2 years), max_result=1000)
I just need to know what should I use for the "date__gt" part (i.e.  date greater than)

Thanks a lot

**Comment by ej2** [comment]
You can use a 'Where' like so:
`invoices = Invoice.where("TxnDate > '2019-01-01'", qb=client) `
