### ISSUE TITLE
CDC breaks when there are no changes

### ISSUE THREAD

**Issue by shoebox639** [sidecars/python-quickbooks#149]
When I do:
```python
change_data_capture([Bill], some_date_time, qb=qb)
```

I get the following error:

```
IndexError: list index out of range
Traceback (most recent call last):
  [...more stack trace]
  File "/[private]/virtualenvs/avm-env/lib/python3.6/site-packages/quickbooks/cdc.py", line 32, in change_data_capture
    qb_object_name = [x for x in query_response_dict if x in cdc_class_names][0]
IndexError: list index out of range
```

It seems to be caused by the CDC request not returning a `Bill` object when there are no changes for that entity within the given timestamp.

Testing on the API explorer, I get this when I call CDC for Bills:

```json
{
  "CDCResponse": [
    {
      "QueryResponse": [
        {}
      ]
    }
  ],
  "time": "2019-03-13T10:24:05.179-07:00"
}
```

My guess is that this is a recent API change by Intuit, since the only other CDC related issue the one creating feature in 2015.

**Comment by ej2** [comment]
Resolved in 0.8 release.
