### ISSUE TITLE
Oauth2SessionManager.update_tokens does not update session

### ISSUE THREAD

**Issue by Hekaiyo** [sidecars/python-quickbooks#150]
Currently, the Oauth2SessionManager does not update the rauth OAuth2Session access token when the update_tokens() method is called.

This means that calling methods such as refresh_access_tokens() doesn't actually refresh the access token used to make requests, resulting in potentially authorization failures. 

My current fix is to just stick this inside update_tokens():
```
        if self.started:
            self.session.access_token = self.access_token
```

**Comment by ej2** [comment]
No longer relevant since OAuth Session Manager has been removed.

**Comment by marc-thomas** [comment]
What is the correct way to update refresh tokens?

**Comment by morenoh149** [comment]
@marc-thomas https://stackoverflow.com/a/59595149/630752
```
Why does my refresh token expire after 24 hours?

Stale refresh tokens expire after 24 hours. Each time you refresh the access_token a new refresh_token is returned with a lifetime of 100 days. The previous refresh_token is now stale and expires after 24 hours. When refreshing the access_token, always use the latest refresh_token returned to you.
```
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/faq
