### ISSUE TITLE
Creating `TaxAgency` from the API doesn't work

### ISSUE THREAD

**Issue by arulz62** [sidecars/python-quickbooks#151]
I am having some issues creating a `TaxAgency` using the API. At first I tried:

```
new_tax_agency = qbo.TaxAgency()
new_tax_agency.DisplayName = 'Agency1'
new_tax_agency.save(qb=auth_service.client)
```

But then [validating the QBO object fails](https://github.com/sidecars/python-quickbooks/blob/master/quickbooks/client.py#L308).

After some investigation, I discovered `_BUSINESS_OBJECTS` doesn't contain `TaxAgency`, hence I decided to just append it. After trying again, I get a new validation error:

```
Business Validation Error: Account numbers must follow the plan compatable numbering system.
```

I am a bit clueless as to what this means, and any help will be really appreciated. Has anyone successfully created `TaxAgency`s using the API?

**Comment by ej2** [comment]
Resolved in 0.8 release.
