### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by jaredthecoder** [sidecars/python-quickbooks#154]
Hello, @grantmcconnaughey, @ej2, @deathnfudge:

Is this repository still actively maintained. It doesn't seem to be.

There are issues and pull requests as recent as yesterday, but no commits since October 2018, and that was only a badge version tweak on the README.

**Comment by ej2** [comment]
This is an active project. Work and family commitments have made it difficult to find time to maintain this project.  I am currently working on all the issues and pull requests. I should have a new release by the end of the week.

**Comment by jaredthecoder** [comment]
@ej2 Is there anything I can do to help?

I recently started on a project that will integrate with Quickbooks, and I am a Python fanatic. I don't really want to deal with C# or Java (which Intuit supports themselves).

**Comment by ej2** [comment]
@jaredthecoder thanks for the offer! There are a number of API features that have not been implemented. [This issue](https://github.com/sidecars/python-quickbooks/issues/129) asked about adding the Preferences object.

**Comment by justmobilize** [comment]
@ej2 I am also happy to help :)
