### ISSUE TITLE
Where is the AuthClient?

### ISSUE THREAD

**Issue by zikphil** [sidecars/python-quickbooks#155]
Did something happen with the latest push to master? It's referencing a AuthClient object that is nowhere to be found in the code base.

**Comment by ej2** [comment]
AuthClient is in intuit-oauth. Follow the [Oauth 2.0 guide](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0) for installation and configuration. I will update the documentation to make that more clear.

**Comment by jaredthecoder** [comment]
The documentation in the README LGTM and I was able to follow, @ej2.
