### ISSUE TITLE
Plus sign '+' in email address breaks .send() method

### ISSUE THREAD

**Issue by ridwan-kazi** [sidecars/python-quickbooks#162]
I am able to create a customer with a '+' in their email address, but when I attempt to use that email to send the new customer an invoice I get an invalid email error. Does Quickbooks not support plus signs in emails?

**Comment by ej2** [comment]
I am not sure. You should ask on the [official Intuit developer forums](https://help.developer.intuit.com/s/) and see if they can answer your question.

**Comment by ridwan-kazi** [comment]
I actually looked through your `SendMixin` class and noticed that the email are not url encoded, so encoded my input emails and it worked. I'll make a PR with the change and also include the allow credit card updated from the other ticket I made if thats cool with you.

**Comment by ej2** [comment]
Sounds good!
