### ISSUE TITLE
How to get refresh token programmatically?

### ISSUE THREAD

**Issue by iocuydi** [sidecars/python-quickbooks#178]
Hi, how can I use this api to get the refresh token programmatically? I can get one issued from the developer site, but it will eventually expire, breaking my application, unless I insert another one at exactly the right time. Presumably there is a way to do everything programmatically? Or am I misunderstanding the point of the refresh token?

Thanks!

**Comment by morenoh149** [comment]
this a token that lasts 100 days and another that lasts 1 hour. I think you refresh the 100 day one programmatically.

**Comment by iocuydi** [comment]
I think you are correct. Do you know how to refresh the 100 day one programmatically? There does not seem to be any documentation on this, only a description of how to get it via their GUI

**Comment by ej2** [comment]
> The refresh token itself can last up to 100 days before it expires, and then the user needs to sign in and grant consent again or you can get a new one programmatically using the Refresh Token API before the 100-day refresh token expires. 

[https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#step-5-exchange-authorization-code-for-refresh-and-access-tokens](url)

You **cannot** refresh the 100 day token. This is done for security reasons.

**Comment by ej2** [comment]
The [documentation](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#refresh-the-token) seems to indicate that calling Refresh will keep the token working.

**Comment by morenoh149** [comment]
the django example here has an example of refreshing from the client https://github.com/IntuitDeveloper/SampleOAuth2_UsingPythonClient/blob/master/app/templates/connected.html#L30 shouldn't be too hard to translate into api-side on a cron schedule
