### ISSUE TITLE
Reports API

### ISSUE THREAD

**Issue by grumpy-curmudgeon** [sidecars/python-quickbooks#2]
To implement reports, you can add this function to client.py:

```
def get_report(self, report_type, qs):
        url = self.api_url + "/company/{0}/reports/{1}".format(self.company_id, report_type)
        result = self.make_request("GET", url, params=qs)
        return result
```
and make two other changes to make_request:
[1] 
```
def make_request(self, request_type, url, request_body=None, content_type='application/json', params=None):
```
[2]
```
if not params:
            params = {}
```
(If I knew how to do a pull request, I would. Thanks for building this!)

Here's my sample function that handles a P+L report response. This is not for production, just to save you some time when you get around to it.

    self._pldataset = {
            'dates': [],
            'data': []
        }

     pldata = QuickBooksExtended.get_report(self._self, 'ProfitAndLoss', {
                'date_macro' : 'This Fiscal Year',
                'accounting_method' : 'Cash',
                'summarize_column_by': 'Month'
                })

    self._massagePLRowData(pldata)  <-- recursive, and relies on member var for storage 
    self._savePLRowData()   <-- just dumps into database

    # note: very recursive...
    def _massagePLRowData(self, pileOfRows):

        if isinstance(pileOfRows, list):
            for x in pileOfRows:
                self._getPLRowData(x)

        else:

            if 'Rows' in pileOfRows.keys():
                self._getPLRowData(pileOfRows['Rows'])

            if 'Row' in pileOfRows.keys():
                self._getPLRowData(pileOfRows['Row'])

            if 'Summary' in pileOfRows.keys():
                self._getPLRowData(pileOfRows['Summary'])

            if 'ColData' in pileOfRows.keys():
                d = dict()
                d['name'] = pileOfRows['ColData'][0]['value']
                vals = []
                for x in pileOfRows['ColData'][1:]:
                    vals.append(x['value'])
                d['values'] = vals
                self._pldataset['data'].append(d)

            if 'Columns' in pileOfRows.keys():
                self._getPLRowData(pileOfRows['Columns'])

            if 'Column' in pileOfRows.keys():
                for x in pileOfRows['Column']:
                    if 'MetaData' in x.keys():
                        self._pldataset['dates'].append(x['MetaData'][0]['Value'])

**Comment by ej2** [comment]
Thanks for the input... I will look into adding this.

**Comment by zimkies** [comment]
@ej2 any thoughts on my above PR? Will be happy to make changes if you feel they are necessary

**Comment by ej2** [comment]
If you will submit a pull request (including tests) I will get it added in. Thanks.

**Comment by ej2** [comment]
PR has been merged
