### ISSUE TITLE
How to upload attachments with bills?

### ISSUE THREAD

**Issue by asavpatel92** [sidecars/python-quickbooks#21]
Can someone point me to the code or sample which shows how to upload an attachment with the bill?

Thanks,
Asav

**Comment by ej2** [comment]
Support for attachments was added to version 0.4.0. I am not familiar with how it works. Maybe @Tusky could provide an example?

**Comment by Tusky** [comment]
My usage is this:

            attachment = Attachable()
            attachment.AttachableRef = [{'EntityRef': {'type': 'Bill', 'value': quickbooks_bill_id}}]
            attachment.FileName = "Your file name"
            attachment._FilePath = "The full path to the file"
            attachment.ContentType = 'application/pdf'
            attachment.save()

**Comment by ej2** [comment]
Added documentation for attachments to the readme.
