### ISSUE TITLE
Singleton Pattern Dangerous?

### ISSUE THREAD

**Issue by jproffitt** [sidecars/python-quickbooks#23]
I love what you've done here, and I'm trying to use this in a django project, but the singleton pattern really worries me.

Say you have 2 different users that each connect to their own QuickBooks account. Say those 2 users connect to the django website at roughly same time. The first user who hits the page, will connect his quickbooks account, and will be about to do some operation. The second user will then need to connect his quickbooks account, which then changes the tokens on the singleton object to his own tokens. If the first user is just about to do his operation, all of a sudden, that operation will be done on the second user's quickbooks account. VERY BAD.

Am I misunderstanding this? As far as I know, you almost never want to have global variables in a django project because django is a long-running process. Those global variables will stick around between requests, AND between users/sessions.

I am thinking about forking this project, and refactoring it to not use singletons, because I love how everything else in the project is done.

**Comment by ej2** [comment]
I believe you are correct. The project I designed the library for, uses only one QuickBooks account so I have never encountered this issue. There is a pull request that fixes the problem (https://github.com/sidecars/python-quickbooks/pull/15). I will work on getting it merged in.

**Comment by jproffitt** [comment]
Ah, that pull request is exactly what I'm looking for. I will use that fork until it gets merged in

**Comment by Tusky** [comment]
This would be amazing, if it were implemented, my fix is still waiting for implementation though also

**Comment by zimkies** [comment]
I can confirm that this singleton pattern is indeed a big problem. I'm currently using this library in a project, and I'm running into a similar but even more common problem.

If 2 users independently authorize their quickbooks accounts within my application, the first user to authenticate will always have their realm id used in api requests, regardless of which user is trying to make api calls. 

@jproffitt is there a reason a singleton pattern is needed here, or will simply removing [this __new__ line](https://github.com/sidecars/python-quickbooks/blob/master/quickbooks/client.py#L57) be sufficient to fix this?

**Comment by jproffitt** [comment]
@zimkies I don't believe removing that line will fix it. It will indeed "reset" itself every time you initialize the class, but it will reset it for every user using the application at the same time. So if one user does an action that initializes the class, then another action to do some work. Then at the same time, another user does the action to initialize the class, it will reset the class for the first user as well. Since all users will still be sharing the same class.

Basically, removing that line may help a little bit, if you always re-initialize the class before each quickbooks call, but there is still a major problem if 2 users try to initialize the class at roughly the same time.

I believe in general, singleton patterns should never be used in long-running or multi-thread projects like django.

I think the best way to fix this is exactly what this PR does: https://github.com/sidecars/python-quickbooks/pull/15. Pass around a unique quickbooks instance to every QB call.

**Comment by zimkies** [comment]
@jproffitt thanks a lot for the insight, I had a feeling that was the case. I guess we'll go ahead and use your fork for now, thanks for submitting that fix.

**Comment by jproffitt** [comment]
@zimkies you're welcome. But that is not my fork, it is @peterlai fork. I have not used the fork yet, so I am not sure it works, but looking just looking at it, it seems to be the correct solution.

**Comment by Tusky** [comment]
it seems so strange that after a month this is still at large, even though it's a pretty serious issue. Given most of the work is already done, and some failing tests need to be fixed, I would be more than happy if this were to be closed already.

**Comment by ej2** [comment]
Updated last night. Enjoy!
