### ISSUE TITLE
ValidationFault for Invoices

### ISSUE THREAD

**Issue by gummoe** [sidecars/python-quickbooks#24]
**Issue:** 
QuickBooks returns a ValidationFault error when POSTing Invoices. 

**Sample Response:**
`{u'type': u'ValidationFault', u'Error': [{u'Message': u'Request has invalid or unsupported property', u'code': u'2010', u'Detail': u'Property Name:Can not instanti specified is unsupported or invalid'}]}`

Information on this error [here](https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/error_handling)

**Sample code that generates this error:**
`invoice = Invoice()`
`invoice.CustomerRef = unicode(61)`
`invoice.save()`

**Analysis:**
It seems that the package is either failing to instantiate the Invoice object itself, or is mistakenly sending an additional 'field' called `Can not instanti` with its POST call. I think that the former is most likely, but I haven't been able to nail down where the error is occurring. I've tried setting the `CustomerRef` value to:
- A simple integer
- Unicode of integer
- An actual Customer object

but I get the same behavior for each approach. Removing the `CustomerRef` and attempting to POST an Invoice with no other attributes causes QuickBooks to return a `Required param missing` error. I am successfully able to POST and GET Customer objects, so I do not believe that this is an issue with credentials, environment settings, etc. Any help would be greatly appreciated - it is entirely possible that I am simply misusing the Invoice object in a way that I can't identify.

**Comment by ej2** [comment]
CustomerRef is a Ref object. Either query quickbooks for a Customer and use the to_ref method or create a Ref object and set it's value property to the customer id. Examples below:

```
customer = Customer.get(1, qb=client)
invoice.CustomerRef = customer.to_ref()
```

```
customer_ref = Ref()
customer_ref.value = 61
invoice.CustomerRef = customer_ref
```

**Comment by gummoe** [comment]
This is perfect - thank you very much @ej2 ! Would you be amenable to me adding a section to the README.rst for working with Ref objects?

**Comment by gummoe** [comment]
I went ahead and wrote a quick section using your examples in a branch - how would you like me to contribute @ej2 ? I'm happy to just post the edits to the README here if you prefer that over a branch and a PR.
