### ISSUE TITLE
CDC Support

### ISSUE THREAD

**Issue by jhansen-tt** [sidecars/python-quickbooks#3]
Do you know if there are any plans to support the Change Data Capture API?
https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/change_data_capture

**Comment by ej2** [comment]
Had not planned on it but I will look into it.

**Comment by asavpatel92** [comment]
That would be pretty helpful for syncing operations to other apps. are there any updates on this?

**Comment by ej2** [comment]
CDC support added in version 0.6.0
