### ISSUE TITLE
Updating purchase

### ISSUE THREAD

**Issue by mbierma** [sidecars/python-quickbooks#31]
I have a purchase object that I would like to modify and save. The purchase object contains a Line attribute (PurchaseLine) which in turn contains an AccountBasedExpenseLineDetail attribute. The AccountBasedExpenseLineDetail is a Ref object, which means that it contains a few attributes by default (value, name, type). 

When saving the purchase object, I get an error messages that indicates quickbooks doesn't recognize some of the attributes given. To work around this issue, I can delete these extra attributes before saving the purchase object:

```
for line in purchase.Line:
    del line.AccountBasedExpenseLineDetail.name
    del line.AccountBasedExpenseLineDetail.value
    del line.AccountBasedExpenseLineDetail.type
purchase.save(qb=client)
```

**Comment by ej2** [comment]
That is definitely an issue. The AccountBasedExpenseLineDetail should be a AccountBasedExpenseLineDetail object not a ref object. I will work on getting it fixed.

**Comment by mbierma** [comment]
thank you!
