### ISSUE TITLE
Convert Objects to JSON

### ISSUE THREAD

**Issue by shaunc869** [sidecars/python-quickbooks#36]
Hi, awesome library, is there an easy way to convert these to JSON objects? Thanks!

**Comment by ej2** [comment]
Hey Shaun,

Not sure what you are asking... If you just need JSON data, the quickbooks
API will return JSON. No need to use a library. Let me know if that answers
your question.

Later,
Edward

**Comment by grantmcconnaughey** [comment]
@shaunc869 

Every object has a `to_json` method. That comes from [here](https://github.com/sidecars/python-quickbooks/blob/master/quickbooks/mixins.py#L7).
