### ISSUE TITLE
Purchase order: Property Name:Unrecognized field "BillableSt specified is unsupported or invalid

### ISSUE THREAD

**Issue by RemyAlves** [sidecars/python-quickbooks#38]
Hi,
First of all thanks for this beautiful repo, it helped me win so much time on my qb integration.

Im trying right now to create purchase order, but after putting (I think) every correctly, I end up on this error : "2010: Property Name: Unrecognized field "BillableSt specified is unsupported or invalid".
I tryed to remove line 51 or purchaseorder.py:PurchaseOrderLine : ' self.BillableStatus = "" ', seem to solve this problem.

But after doing so, I got an other problem, more strange and can't find a way to do it. I tried to take exemple from the test but don't work.

2010: Property Name:Can not deserialize instance of com.intuit.schema.finance.v3.LineDetailTypeEnum out of START_OBJECT token specified is unsupported or invalid

I'm dropping my code right here, tell me what you think about it, if its on my side (probably) or yours.
Thanks a lot ! :)

```
    po = PurchaseOrder()

    vendor_obj = Ref()
    vendor_obj.value = "21"
    vendor_obj.name = "Cali'Remy_Remy_Alves"
    po.VendorRef = vendor_obj

    expenseAccount = Ref()
    expenseAccount.name = "Cost of Goods Sold"
    expenseAccount.value = "60"
    po.APAccountRef = expenseAccount

    line = PurchaseOrderLine()
    line.LineNum = 1
    line.Amount = 42
    line.Description = "Yolo description"

    line.DetailType = ItemBasedExpenseLineDetail()
    item = Item.all(max_results=1, qb=client)[0]
    line.DetailType.ItemRef = item.to_ref()

    po.Line.append( line )

    po.save(qb=client)
```

Have a good day

**Comment by RemyAlves** [comment]
BillableStatus seem to only exist in ItemBasedExpenseLineDetail, should not be in PurchaseOrderLine too.

https://developer.intuit.com/docs/api/accounting/PurchaseOrder

**Comment by ej2** [comment]
It is a bug in the python-quickbooks library, I found it earlier today. The good news is I have been working on a fix and it should be ready soon.

**Comment by RemyAlves** [comment]
Thank you, keep me updated when it will be possible to do PO :)

**Comment by ej2** [comment]
Just released an update. Should fix your issue.

**Comment by RemyAlves** [comment]
I will test and come back to you if it does. Thanks a lot !

**Comment by RemyAlves** [comment]
@ej2 : Nope...
2010: Property Name:Can not construct instance of com.intuit.schema.finance.v3.PurchaseOrderSt specified is unsupported or invalid

I followed the exemple you put in test, tried some different stuff, and still have this issue...

Also, when I try to use this line :
taxcode = TaxCode.all(max_results=1, qb=self.qb_client)[0]
I get this error :
(Error: global name 'self' is not defined)


This is my code :

		po = PurchaseOrder()

		detail_line = ItemBasedExpenseLine()
		detail_line.Amount = ordered_products[0].product.sell_adult_price * ordered_products[0].adult_quantity
		detail_line.ItemBasedExpenseLineDetail = ItemBasedExpenseLineDetail()
		detail_line.ItemBasedExpenseLineDetail.BillableStatus = "Billable"

		detail_line.ItemBasedExpenseLineDetail.UnitPrice = ordered_products[0].product.sell_adult_price
		detail_line.ItemBasedExpenseLineDetail.Qty = ordered_products[0].adult_quantity
		detail_line.ItemBasedExpenseLineDetail.CustomerRef = Ref()
		detail_line.ItemBasedExpenseLineDetail.CustomerRef.value = request.user.userdetails.qb_id
		detail_line.ItemBasedExpenseLineDetail.ItemRef = Ref()
		detail_line.ItemBasedExpenseLineDetail.ItemRef.value = ordered_products[0].product.qb_id_adult
		detail_line.ItemBasedExpenseLineDetail.TaxCodeRef = Ref()
		detail_line.ItemBasedExpenseLineDetail.TaxCodeRef.value = 1

		po.Line.append( detail_line )
		po.VendorRef = Ref()
		po.VendorRef.value = ordered_products[0].product.furnisher.qb_id
		po.APAccountRef = Ref()
		po.APAccountRef.value = "60"

		po.save(qb=client)

**Comment by ej2** [comment]
Sometimes the errors coming back don't contain all the information. Try running the created json through the QB API explorer (https://developer.intuit.com/v2/apiexplorer) to see the entire error message returned from QB API. You can get the json like so:
`print po.to_json()`

Also post the json here and I will verify that it is correct too.

**Comment by RemyAlves** [comment]
Not any usefull data using the API explorer...

{
    "APAccountRef": {
        "name": "",
        "type": "",
        "value": "60"
    },
    "CustomField": [],
    "DocNumber": "",
    "DueDate": "",
    "ExchangeRate": 1,
    "GlobalTaxCalculation": "TaxExcluded",
    "Line": [
        {
            "Amount": 140,
            "CustomField": [],
            "DetailType": "ItemBasedExpenseLineDetail",
            "ItemBasedExpenseLineDetail": {
                "BillableStatus": "Billable",
                "CustomerRef": {
                    "name": "",
                    "type": "",
                    "value": "31"
                },
                "ItemRef": {
                    "name": "",
                    "type": "",
                    "value": "67"
                },
                "Qty": 2,
                "TaxCodeRef": {
                    "name": "",
                    "type": "",
                    "value": 1
                },
                "TaxInclusiveAmt": 0,
                "UnitPrice": 70
            },
            "LineNum": 0,
            "LinkedTxn": []
        }
    ],
    "LinkedTxn": [],
    "POStatus": "",
    "PrivateNote": "",
    "SyncToken": 0,
    "TotalAmt": 0,
    "TxnDate": "",
    "VendorRef": {
        "name": "",
        "type": "",
        "value": "20"
    },
    "domain": "QBO",
    "sparse": false
}

**Comment by ej2** [comment]
Set POStatus to "Open", "Closed", or None and try it again.

**Comment by RemyAlves** [comment]
What a pro ! (y)
It work. Perhaps set POStatus to "Open" as default, to have the same behavior as the QBO GUI and don't get people lost. The error report of QBO API is really bs... How did you found out for POStatus ? It's not even in the "required" arguments on the doc

**Comment by RemyAlves** [comment]
Not possible to fill the vendor mail field ? Neither to get the pdf or send it by mail ?

**Comment by RemyAlves** [comment]
Because its not possible to delete all PO on QBO, I tried to do it with a short code, but ended up again with this error :
2010: Property Name:Unrecognized field "BillableSt specified is unsupported or invalid

from quickbooks.quickbooks.batch import batch_delete

po = PurchaseOrder.all(max_results=28, qb=client)
result = batch_delete(po, qb=client)
