### ISSUE TITLE
Help Getting Oauth to work

### ISSUE THREAD

**Issue by bbmak** [sidecars/python-quickbooks#39]
I have tried to play around with the python-quickbooks lib, but I can figure out how to get django work. Everytime, I run the script, I get this error. 

"oauth_token = request.GET['oauth_token']" 
NameError: name 'request' is not defined

I read the documentation, request is from django http.request.
I have my django 1.10 library installed, but just cant figure out how to import lib into the quickbooks script.

I tried this, and it is not working.

from django.http import *
from django.utils.html import *
from django.utils.http import *

Are there a more detail guideline for this?

**Comment by ej2** [comment]
You shouldn't need to import anything for request. Create a normal view with request as the first parameter (See https://docs.djangoproject.com/en/1.10/topics/http/views/ if you need help with Django views). After OAUTH happens, the quickbooks site will redirect back to the CALLBACK_URL (which you will want to be the url of the view you created).  The request will contain the values you need to store.

**Comment by bbmak** [comment]
Isn't possible to give a working example of the view.py?

**Comment by ej2** [comment]
First we need somewhere to store the oauth request token, access token, and secrets
```
# --------- models.py ----------------------
class AuthorizeStore(models.Model):
    oauth_token = models.CharField(max_length=100, null=True, blank=True)
    oauth_verifier = models.CharField(max_length=100, null=True, blank=True)
    realm_id = models.CharField(max_length=100, null=True, blank=True)
    active = models.BooleanField(default=True)
    authorize_url = models.CharField(max_length=500)
    access_token = models.CharField(max_length=100, null=True, blank=True)
    access_token_secret = models.CharField(max_length=100, null=True, blank=True)  # This value should be encrypted
    request_token = models.CharField(max_length=100, null=True, blank=True)
    request_token_secret = models.CharField(max_length=100, null=True, blank=True)  # This value should be encrypted
client_key = models.CharField(max_length=100, null=True, blank=True)
    client_secret = models.CharField(max_length=100, null=True, blank=True)  # This value should be encrypted
```

Specify two views, first one to get the authorize url and the second to handle the callback.
```
# ---------- views.py ----------------------
def authorize(request):
    if request.method == "POST":
        # The view Quickbooks OAUTH process will redirect to when complete
        callback_url = reverse("authorize_callback")
        client_key = request.POST.get('key')
        client_secret = request.POST.get('secret')


        # Setup Quickbooks client
        quickbooks_client = QuickBooks(
            sandbox=is_sandbox(),
            consumer_key=client_key,
            consumer_secret=client_secret,
            callback_url=callback_url,
        )

        # Get quickbooks authorize url
        authorize_url = quickbooks_client.get_authorize_url()

        # Store authorize url, request token, and request token secret
        AuthorizeStore.objects.create(
            authorize_url=authorize_url,
            request_token=quickbooks_client.request_token,
            request_token_secret=quickbooks_client.request_token_secret,
            created_by=request.user
        )

        # Redirect to quickbook authorize url for oauth
        return redirect(authorize_url)

    return TemplateResponse(request, "authorize.html")


def authorize_callback(request):
    # Get active auth store
    auth_store = AuthorizeStore.objects.get(active=True)

    # Setup Quickbooks client
    quickbooks_client = QuickBooks(
        sandbox=is_sandbox(),
        consumer_key=auth_store.client_key,
        consumer_secret=auth_store.client_secret,
    )

    # Pass in required parameters for get_access_tokens
    quickbooks_client.authorize_url = auth_store.authorize_url
    quickbooks_client.request_token = auth_store.request_token
    quickbooks_client.request_token_secret = auth_store.request_token_secret
    quickbooks_client.set_up_service()

    quickbooks_client.get_access_tokens(request.GET['oauth_verifier'])

    # Save tokens and secret in auth_store for later use.
    auth_store.oauth_token = request.GET['oauth_token']
    auth_store.oauth_verifier = request.GET['oauth_verifier']
    auth_store.access_token = quickbooks_client.access_token
    auth_store.access_token_secret = quickbooks_client.access_token_secret
    auth_store.realm_id = request.GET['realmId']
    auth_store.save()

    return render(request, "complete.html")
```

authorize.html - simple form
```
<html>
  <body>
    <form class="form-horizontal" method="post" action="">
Client Key: <input type="text" name="key">
      Client Secret: <input type="text" name="secret">
      
      <button type="submit">Authorize Quickbooks</button>
      {% csrf_token %}
    </form>
  </body>
</html>
```

complete.html - page displaying that the process is complete
```
<html>
  <body>
    Quickbooks authorization complete!
  </body>
</html>
```


Helper functions 
```
# ---------- utils.py ----------------------
def is_sandbox():
    return not settings.PRODUCTION


def get_quickbooks_client():
    auth_store = AuthorizeStore.objects.get(active=True)

    client = QuickBooks(
        sandbox=is_sandbox(),
        consumer_key=settings.QUICKBOOKS_CLIENT_KEY,
        consumer_secret=settings.QUICKBOOKS_CLIENT_SECRET,
        access_token=auth_store.access_token,
        access_token_secret=auth_store.access_token_secret,
        company_id=auth_store.realm_id,
    )

    return client

```

Get list of customers 
```
client = get_quickbooks_client()
customers = Customer.all(qb=client)

**Comment by bbmak** [comment]
Awesome! Thanks, I'll play around with your working sample.

**Comment by reidelon** [comment]
Hello i watching your utils.py file and i wnat to use it but i dont know hoe to get the client_key? Can you tell? thanks

**Comment by ej2** [comment]
The client_key (also known as Oauth Consumer Key) can be obtained from Intuit's developer portal: https://developer.intuit.com

**Comment by reidelon** [comment]
Hello sorry i just noticed the utils.py is tied to the django example
above, in just want make a client o connect to my app in quickbook and
read, write Account just ply wtih all this and learn, I just have 3 thing
to setup my client to quickbook:

App Token

OAuth Consumer Key

OAuth Consumer Secret

are they enough to do what i wnat?


2016-09-03 13:46 GMT-04:00 Edward Emanuel <notifications@github.com>:

**Comment by reidelon** [comment]
I noticed in some examples on GitHub about python-quickbook in the tiem to
make client using this variable:

access_token_secret
===================================
 Where do i get it ?

here is the example:

client = QuickBooks(
    sandbox=True,
    consumer_key=QUICKBOOKS_CLIENT_KEY,
    consumer_secret=QUICKBOOKS_CLIENT_SECRET,
    access_token=access_token,
    access_token_secret=access_token_secret,
    company_id=realm_id
)



2016-09-03 13:59 GMT-04:00 Tomahawk <reidelon@gmail.com>:

**Comment by ej2** [comment]
@reidelon did you get the example working?

**Comment by bbmak** [comment]
Not yet.
Reading the django tutorials and try to get it to work. I still play around the code, and I am new to django too.

**Comment by bbmak** [comment]
Do I put the authorize.html in templates folder?

**Comment by ej2** [comment]
Yes

**Comment by rschwiebert** [comment]
I have been trying things like this for hours and I still don't understand where `oauth_verifier` comes from in the request.GET data.  What's the deal?!

**Comment by bbmak** [comment]
Hi ej2,
When I entered the client key, and client secret on the authorize page, I got an error. 
Forbidden (403)
CSRF verification failed. Request aborted.
CSRF token missing or incorrect.

Do you know how to I fix it?

**Comment by rschwiebert** [comment]
The example above should probably add the created_by field to the model.

I'm trying the setup above now, but before `authorize_callback` is reached, the browser redirects to an Intuit page asking for me to enter my password. Maybe this is only a problem for the sandbox(?) but I would have thought the is_sandbox=True would have taken care of that.

**Comment by reidelon** [comment]
Thanks for you cooperation

2016-09-03 13:09 GMT-05:00 Tomahawk <reidelon@gmail.com>:

**Comment by ej2** [comment]
The example provided is not 100% complete. Please do not use it as is for production. You will need to customize it for your situation. 

Authorize should redirect to Intuit for authorization. After you login and authorize your application on Intuit's site, it will redirect back to the callback_url, passing oauth_token, oauth_verifier, and realmId in the query string. [Intuit's article](https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/0085_develop_quickbooks_apps/0004_authentication_and_authorization/connect_from_within_your_app) explains the whole workflow.

**Comment by ej2** [comment]
@bbmak did you figure out your CSRF token issue?

**Comment by reidelon** [comment]
Nop

2016-09-14 9:54 GMT-05:00 Edward Emanuel <notifications@github.com>:

**Comment by deathnfudge** [comment]
Django has a built in template tag {% csrf_token %} that should be included in your forms. For information on how to properly use it check out this page https://docs.djangoproject.com/en/1.10/ref/csrf/

**Comment by reidelon** [comment]
ok thanks

2016-09-14 10:25 GMT-05:00 deathnfudge <notifications@github.com>:

**Comment by bbmak** [comment]
Hi ej2,
No, not yet. 

deathnfudge,
Thx, I'll take a look of that.

**Comment by bbmak** [comment]
Question, can you tell me what is the % mean in this block of code under client.py? I try to upload an attachment to QBO. % (boundary, request_body, boundary, binary_data, boundary)
When I read QBO's documentation, i got confuse on their request_body.

`request_body = textwrap.dedent(
                """
                --%s
                Content-Disposition: form-data; name="file_metadata_01"
                Content-Type: application/json
                %s
                --%s
                Content-Disposition: form-data; name="file_content_01"
                Content-Type: application/pdf
                %s
                --%s--
                """
            ) % (boundary, request_body, boundary, binary_data, boundary)

        req = self.session.request(
            request_type, url, True, self.company_id, headers=headers, params=params, data=request_body)`

**Comment by ej2** [comment]
[http://stackoverflow.com/questions/997797/what-does-s-mean-in-python](http://stackoverflow.com/questions/997797/what-does-s-mean-in-python) - stackoverflow post explaining what %s does. 

[https://docs.python.org/3/library/stdtypes.html#string-formatting-operations](https://docs.python.org/3/library/stdtypes.html#string-formatting-operations) - official python documentation on %s.

**Comment by bbmak** [comment]
Thx ej2,
Got it work. Are there a function to link the existing attachment in QBO? I am able to upload attachments now, but not able to link to an invoice yet.

**Comment by deone** [comment]
Hello,

I tried your Django example but kept getting this error:

`HTTPSConnectionPool(host='oauth.intuit.com', port=443): Max retries exceeded with url: /oauth/v1/get_request_token?oauth_version=1.0&oauth_nonce=731e7a3289a9948675c8854e21e14c56870ae372&oauth_timestamp=1475962929&oauth_signature=iOi9m2e844Rx3GRU3rtNflseHGY%3D&oauth_consumer_key=***********&oauth_signature_method=HMAC-SHA1&oauth_callback=http%3A%2F%2Flocalhost%3A5000%2Fcallback%2F (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10da9dd90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))`

Any ideas?

**Comment by ej2** [comment]
@deone what statement is causing the error?

**Comment by thegoose32** [comment]
Hi @Ej2, in your example above, where does the settings.PRODUCTION in the utils.py get imported from?
