### ISSUE TITLE
Renew Tokens

### ISSUE THREAD

**Issue by mosesmc52** [sidecars/python-quickbooks#40]
Hi,

I'm new with using the quickbooks API. After 180 days the token has expired. How do I renew the quickbooks token?

Moses

**Comment by ej2** [comment]
```
client = QuickBooks(
    sandbox=True,
    consumer_key=QUICKBOOKS_CLIENT_KEY,
    consumer_secret=QUICKBOOKS_CLIENT_SECRET,
    access_token=access_token,
    access_token_secret=access_token_secret,
    company_id=realm_id,
    minorversion=4
)

client.reconnect_account()
```

Not sure why this wasn't in the readme, but I will add it.

**Comment by porn** [comment]
Hey, just a note here: reconnecting the account doesn't work the best when the Quickbooks is run in the singleton mode. Had to call `disable_global()` after the token was reconnected (or restart the webserver)
