### ISSUE TITLE
Quickbooks Desktop API Support?

### ISSUE THREAD

**Issue by tech4him1** [sidecars/python-quickbooks#41]
Does python-quickbooks work with Quickbooks Desktop, or only Quickbooks Online?

**Comment by ej2** [comment]
It only works with Quickbooks Online.

**Comment by tech4him1** [comment]
Thanks.

**Comment by tech4him1** [comment]
Do you happen to know of any libraries that do interface with QB Desktop?  I might not have looked well enough, but I was having trouble finding one.

**Comment by ej2** [comment]
The [official Intuit SDK](https://developer.intuit.com/docs/0200_quickbooks_desktop/0400_tools/quickbooks_desktop/download_the_sdk) is the only thing I know of.

**Comment by tech4him1** [comment]
OK, just wanted to check.  Thanks for your time.
