### ISSUE TITLE
Throttle Exceeded error incorrectly reported

### ISSUE THREAD

**Issue by ryphill** [sidecars/python-quickbooks#43]
When QuickBook's rate limit is exceeded the client receives the error response but raises the exception for when it cannot read the json response instead of reporting that the request limit has been reached. Provided below is the exception thrown when this occurs:

``` python
QuickbooksException: Error reading json response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2016-10-10T12:14:28.801-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="SERVICE">
        <Error code="3001">
            <Message>message=ThrottleExceeded; errorCode=003001; statusCode=403</Message>
            <Detail>The request limit was reached.  Try again later</Detail>
        </Error>
    </Fault>
</IntuitResponse>
```

It looks like this is happening because the `make_request` method in the `QuickBooks` object expects both success and error response to return json but for the `ThrottleExceeded` error QuickBooks responds with xml.

I am using version 0.5.1 of the library and a sandbox instance on QuickBooks.

**Comment by ryphill** [comment]
Actually, I think this might be a bug on QuickBooks's end since they're responding with xml when the `Accept` header on the request is set to `application/json`.

**Comment by ej2** [comment]
Yes, it is. I told them about it a long time ago: [Requesting json, receiving XML errors](https://intuitdeveloper.lc.intuit.com/questions/1253319-requesting-json-receiving-xml-errors)

**Comment by ryphill** [comment]
I opened a support ticket with them (Case Number 00039761) so hopefully they'll get to the bottom of this soon.

**Comment by ryphill** [comment]
Small update on this from QuickBooks. The throttle error is handled by their Gateway service layer and they have filed an internal issue to address this bug. I will provide any updates from QuickBooks as I receive them.

**Comment by ej2** [comment]
According to Intuit the [Requesting json, receiving XML errors](https://help.developer.intuit.com/s/question/0D5G000004Dk74QKAR/) issue has been fixed.
