### ISSUE TITLE
Unorderable types when saving

### ISSUE THREAD

**Issue by tgehrs** [sidecars/python-quickbooks#44]
When updating a Customer using the same code from tests I am getting an unorderable types error (traceback below). If I print the id's and type(customer.id) I'm getting:
2 <class 'str'>

I'm getting the same error when I test the account object as well.

If this needs updating I am happy to submit a pull request.

`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../python3.5/site-packages/quickbooks/mixins.py", line 71, in save
    if self.Id and self.Id > 0:
TypeError: unorderable types: str() > int()`

**Comment by ej2** [comment]
Sure, submit a PR and I will get it merged. Thanks.

**Comment by ej2** [comment]
Fixed in version 0.5.2
