### ISSUE TITLE
build_choose_clause does not properly escape single quote

### ISSUE THREAD

**Issue by ryphill** [sidecars/python-quickbooks#47]
I've been receiving several `QuickbooksException: Error parsing query` recently when trying to query a list of customers. I tracked it down to the `build_choose_clause` and it looks like it's not properly escaping single quote characters as if I do something like `Customer.choose[u"Someone's Company"], field=u'DisplayName', qb=client)` then I get the following in response:

```
python2.7/site-packages/quickbooks/client.pyc in handle_exceptions(self, results)
    316                 raise SevereException(message, code, detail)
    317             else:
--> 318                 raise QuickbooksException(message, code, detail)
    319
    320     def create_object(self, qbbo, request_body, _file_path=None):

QuickbooksException: Error parsing query
```

I'm using python 2.7.12 and version 0.5.1 of the package. Also it looks like the error detail isn't getting include in the error output but that's a separate issue I think.

I tried passing the string directly to the `build_choose_clause` function and you can see the quote is not escaped:

``` python
choices = [u"Someone's Company"]
build_choose_clause(choices, u'DisplayName') # "DisplayName in ('Someone's Business')"
```

**Comment by ej2** [comment]
Fixed in version 0.5.3
