### ISSUE TITLE
Unable to download Invoice PDF

### ISSUE THREAD

**Issue by rszemplinski** [sidecars/python-quickbooks#53]
Hey guys,

So I realized that I am unable to download a Invoice PDF because in the `QuickbooksPdfDownloadable` object its method `download_pdf` sets its own Quickbooks object which doesn't contain the correct authorization vars. Is there anyway you could fix this fairly soonish?

Thanks!

**Comment by ej2** [comment]
Not sure when I will be able to get to it. If you want to submit a PR, I will get it merged in.

**Comment by nikky78** [comment]
Hi, I would like to download an invoice, but i dont find the proper method. I am doing Invoice.download_pdf(qb=client)
, but it sets itself. How do you do please?
