### ISSUE TITLE
Delete Objects

### ISSUE THREAD

**Issue by FabioFleitas** [sidecars/python-quickbooks#56]
I can't seem to find a way to delete an object. Is there with the existing API? If not I can probably submit a PR to do so. Was thinking of creating a `DeleteMixin`.

**Comment by ej2** [comment]
There is not currently a way to delete objects. For some things you can use batch_delete (see readme for details). A DeleteMixin would be a great way to this. Create a PR and I will work on getting it merged in.

**Comment by FabioFleitas** [comment]
Just to confirm, does the `batch_delete` function delete the object in QBO using the `?operation=delete` param?
