### ISSUE TITLE
Can't load PDF after creating PDF File attachable on Bill

### ISSUE THREAD

**Issue by sabrarossman** [sidecars/python-quickbooks#60]
Hi,
I am using the following code:
            # Attach PDF Invoice
            attachable = Attachable()
            attachable.AttachableRef = [{'EntityRef': {'type': 'Bill', 'value': bill.Id}}]
            attachable.FileName = 'InvoiceTemplate.pdf'
            attachable._FilePath = os.path.dirname(os.path.realpath(__file__)) + '/InvoiceTemplate.pdf'
            attachable.ContentType = 'application/pdf'
            attachable.save(qb=self._client)

I get no errors and can see the attachable on the Bill in my sandbox, but when I try to view it I get 'Failed to load PDF document'.  If I attach the pdf file in Quickbooks online in my sandbox I can view or download the attached PDF just fine.  The attachment created through python shows a size of 372.5kb, and the one created through Quickbooks online shows a size of 215.2kb.

Is this a bug or am I missing a step?
Thanks!

**Comment by ej2** [comment]
What version of python are you using? This PR [https://github.com/sidecars/python-quickbooks/pull/59](https://github.com/sidecars/python-quickbooks/pull/59) fixes an issue with Python 3.

**Comment by sabrarossman** [comment]
Version 3.5.2

**Comment by sabrarossman** [comment]
Hi ej2,
I have a filed an issue with Intuit, because I still have not gotten this to work.  Have you been able to successfully attach a pdf document to a bill via the Attachable and view the pdf in quickbooks online?
Thanks,
Sabra

**Comment by ej2** [comment]
I have not used PDF attachments. Most of that code was written by @Tusky.  You might ask him about it. 

You might try printing out the json code using the to_json() method and paste it into the API explorer. Sometimes you can see more detailed error information on the API explorer.

**Comment by subodh-malgonde** [comment]
@Tusky @ej2 

I checked the source code for uploading files and noticed a couple of issues.

1. On [line 267 of `client.py`](https://github.com/sidecars/python-quickbooks/blob/master/quickbooks/client.py#L269), the `Content-Type` of the file has been hardcoded to `application/pdf`. So even if one uploads `jpeg` or `png`, the file shows up as `PDF` on quickbooks online. When we try to open the file on Quickbooks Online, it says - "Unable to load PDF".

2. When I change this to `image/jpeg` while uploading jpg files, the file gets uploaded with the correct Content-Type. However Quickbooks online is unable to open the attachment. A blank image opens up instead. Not able to figure out why this is happening, but I am guessing the source of this error would be same as the problem faced by @sabrarossman, where the uploaded PDFs don't load.

**Comment by sabrarossman** [comment]
We figured out a fix.  
As you mention for Content-Type it needs to match the type of file.  
Content-Transfer-Encoding: base64 needs to be added to the file part of the request
Instead of attachment.read() it needs
data = base64.b64encode(attachment.read())
binary_data = str(data, 'utf-8’)

This creates the correct encoding for the file and allowed us to upload jpegs, pdfs successfully.

**Comment by subodh-malgonde** [comment]
Thanks! Can you illustrate exactly how to add Content-Transfer-Encoding to the file part of the request?

**Comment by sabrarossman** [comment]
Here is the whole updated section from client.py.  Updates in red

            data = base64.b64encode(attachment.read())
            binary_data = str(data, 'utf-8')

            request_body = textwrap.dedent(
                """
                --%s
                Content-Disposition: form-data; name="file_metadata_01"
                Content-Type: application/json

                %s

                --%s
                Content-Disposition: form-data; name="file_content_01"
                Content-Type: application/pdf
                Content-Transfer-Encoding: base64

                %s

                --%s--
                """
            ) % (boundary, request_body, boundary, binary_data, boundary)

**Comment by subodh-malgonde** [comment]
Have opened a PR #66 to fix this issue. Checks say coverage has reduced. I am not sure how to fix this.

**Comment by jroblak** [comment]
I've opened #70 which I think resolves this in a backwards compatible fashion.

**Comment by humrochagf** [comment]
It was still breaking at python 2 but i found a solution that is on PR #91
