### ISSUE TITLE
How fetch all invoices

### ISSUE THREAD

**Issue by kadnan** [sidecars/python-quickbooks#61]
I can see the test code of creating invoices but how do I query QBO database as they mentioned here(https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice)?

Thanks

**Comment by ej2** [comment]
The readme covers all the ways to query data. To get all simply call the "all" method passing in your client, like so:

` invoices  = Invoice.all(qb=client)`
