### ISSUE TITLE
Error when creating a new vendor

### ISSUE THREAD

**Issue by subodh-malgonde** [sidecars/python-quickbooks#63]
I am trying to create a new vendor. Here is a code snippet

```
vendor = Vendor()
vendor.CompanyName = "Test Name"
try:
    vendor.save(qb=client)
except QuickbooksException as e:
   print(e.detail)
```

The following is printed:

> Property Name:Can not instanti specified is unsupported or invalid

However the Vendor object has no property `Name`. What am I doing wrong?

**Comment by ej2** [comment]
I checked the [Quickbooks vendor documentation](https://developer.intuit.com/docs/api/accounting/vendor) and it looks like you need to set DisplayName or one of the other name fields: 
>  The DisplayName attribute or at least one of Title, GivenName, MiddleName, FamilyName, or Suffix attributes are required during create.


Also, you can print out the json for the object you are working with like this:

`vendor.to_json()`

Then paste it into the [QB API explore](https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO)r to get a better idea of the issue.

**Comment by subodh-malgonde** [comment]
Thanks 👍
