### ISSUE TITLE
IDEA: What exactly does enable_global() do?

### ISSUE THREAD

**Issue by jorgeorpinel** [sidecars/python-quickbooks#77]
I recommend you explain the `QuickBooks.enable_global()` (as well as `disable_globals`) in more detail on the README.

I went in the code to see that these toggle a singleton pattern but didn't get that from the README which states "If your consumer_key never changes you can enable the client to stay running" but actually what if I have a single application but several company's I want to open multiple API client connections with? My consumer key never changes but I still don't want singleton.

Just a thought!

**Comment by deathnfudge** [comment]
The `QuickBooks.enable_global()` is there in case you want a singleton. By default, it doesn't use a singleton so if you don't want a singleton, you don't need to use `QuickBooks.enable_global()`.
