### ISSUE TITLE
In client `get_authorize_url` method, `request_token` and `request_token_secret` are set to lists when they should be strings

### ISSUE THREAD

**Issue by whusterj** [sidecars/python-quickbooks#8]
Hi there! Great work on this library.

I believe I have found a bug. I configured the `QuickBooks` client class and ran `get_authorize_url()`, which returned a URL that didn't work. I decoded the URL and saw that the `oauth_token` value was wrapped in a list:

```
https://appcenter.intuit.com/Connect/Begin?oauth_token=[u'qyprdwHrErQQ3Lxj6NeTbtcmhLvL1KeSsphQgWmmn3IgFev']
```

I removed the brackets, tried the URL again, and was able to authorize my QBO app. I inspected `quickbooks.request_token` and `quickbooks.request_token_secret` in the console, and saw that they were also wrapped in lists. Manually unwrapping them from the lists allowed me to continue connecting to the API without issue.

I believe the issue is in `get_authorize_url` where the `request_token` and `request_token_secret` are assigned. They seem to be expecting strings, but are instead getting strings wrapped in lists from `oauth_resp`:

```python
def get_authorize_url(self):
    ...
    response = self.qbService.get_raw_request_token(
           params={'oauth_callback': self.callback_url})

    oauth_resp = parse_qs(response.text)
    
    self.request_token = oauth_resp['oauth_token']
    self.request_token_secret = oauth_resp['oauth_token_secret']

    return self.qbService.get_authorize_url(self.request_token)

```

I printed `oauth_resp` for debugging purposes.

```python
{
    u'oauth_token_secret': [u'WzU87wYNheeDq3lLQJuFMHqPfeyEcJU9dMZQ606w'],
    u'oauth_token': [u'qyprdxWmp4ZbBMZCuiaUXVXTrMDGzFPBRmz9yQLT1NdMLtCz'],
    u'oauth_callback_confirmed': [u'true']
}
```

It's confusing, because I wouldn't expect any of those values to be lists. I wonder if this perhaps an issue/peculiarity of the rauth library? For now, I will probably hack a quick fix and just grab the 0 index from each to make it work.

What are your thoughts?  

Thanks.

**Comment by whusterj** [comment]
Looks like it's actually the `urlparse.parse_qs` method that's the culprit. It parses each single value of the query string to a list. [Here's a StackOverflow question about it](http://stackoverflow.com/questions/1024143/how-to-stop-python-parse-qs-from-parsing-single-values-into-lists).

The following method looks like a straightforward way to get what one would expect, and it should work under Python 2 or 3.

```python
try:  # Python 3
    from urllib.parse import parse_qsl
except ImportError:  # Python 2
    from urlparse import parse_qsl

dict(parse_qsl(query_string))
```

If you think this is the way to go, I'll submit a pull request.

**Comment by grantmcconnaughey** [comment]
Thanks for the report. Fixed in master.

**Comment by whusterj** [comment]
Awesome. Thanks!
