### ISSUE TITLE
New OAuth2 protocal token issue--absence of access_token_secret

### ISSUE THREAD

**Issue by mmack3540** [sidecars/python-quickbooks#82]
It appears the new OAuth2 protocol returns only access_token and refresh_token. Thus, I am unable to initialize the quickbooks-python client with a access_token_secret. 

For new apps, it appears the code will need to be updated for the new requirements effective 7-17-2017.

The new OAuth2 protocol, effective for new apps, is discussed here:
https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app

**Comment by ej2** [comment]
Support for OAuth 2.0 was added in version 0.7.0.
