### ISSUE TITLE
Oauth2SessionManager.get_access_tokens returns invalid_grant

### ISSUE THREAD

**Issue by deoresheetal** [sidecars/python-quickbooks#95]
Hello,
I have following code
```python
def connect(self, event):
            qb_consumer_key=xxxxxxx
            qb_consumer_secret=xxxxxxxxx
            sandbox=True
            base_url='https://quickbooks.api.intuit.com'
            session_manager = Oauth2SessionManager(sandbox=sandbox,
                                                   client_id=qb_consumer_key,
                                                   client_secret=qb_consumer_secret,
                                                   base_url=base_url)
            state_id = str(uuid.uuid4())
            authorize_url = session_manager.get_authorize_url(callback_url,state=state_id)
            state = {
                    "client_id":qb_consumer_key,
                    "client_secret":qb_consumer_secret,
                    "sandbox": sandbox,
                    "base_url":base_url
                    }
            set_state(state_id, state) # stores the state data in cache
            return authorize_url

def callback(event):
            state = get_state(event['state']) #returns the state where state_id == event['state']
            if state:
                auth_code = event.get("code")
                realm_id = event.get("realmId")
                if auth_code:
                    session_manager = Oauth2SessionManager(**state)
                    at = session_manager.get_access_tokens(auth_code)
                    access_token = session_manager.access_token
                    print("access_token", access_token)
```
Its returning {"error":"invalid_grant"}
It could be due to different session_manager objects??

I looked through auth.py, with Oauth1SessionManager we can retrive previous session but I dont see similar option for Oauth2SessionManager.

**Comment by deoresheetal** [comment]
any suggestions on this? please guide as I am stuck on this.

**Comment by cstarner** [comment]
You are correct in that the issue lies in recreating the Oauth2SessionManager object. Both classes (Oauth1SessionManager and Oauth2SessionManager) act like singletons around the actual session object; however this behavior isn't per class; rather it is per instance. 

In other words, it is expected that you would lose session information when recreating a Oauth2SessionManager. Since you need to recall the session within a callback, is there any reason you couldn't just map the state_id to the session object itself?

**Comment by deoresheetal** [comment]
@cstarner Thanks, mapped the session_id to session object, I can access the same session in callback now but still getting same output i.e  {"error":"invalid_grant"}

**Comment by cstarner** [comment]
https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app

`{"error": "invalid_grant"}` indicates that the refresh_token is incorrect. Somehow `auth_code` is not valid.

**Comment by deoresheetal** [comment]
@cstarner Finally done, need to set session_manager.company_id=realm_id before accessing get_access_token as I was not initializing Quickbook client object.

**Comment by patlaureano** [comment]
Hi @deoresheetal. I am encountering the same issue as you regarding "invalid grant" after trying to get_access_tokens. Would you mind elaborating where you had to set the realmId in order to resolve this? Thanks!

**Comment by mark-mishyn** [comment]
Hello @patlaureano.
In your oauth2 callback view:
```
session_manager = Oauth2SessionManager(
    sandbox=True,
    client_id=QUICKBOOKS_CLIENT_ID,
    client_secret=QUICKBOOKS_CLIENT_SECRET,
    base_url=get_base_url())

session_manager.company_id = request.GET.get('realmId')

session_manager.get_access_tokens(auth_code)
```

**Comment by mark-mishyn** [comment]
It would  be great to update the documentation example "Manually connecting with OAuth version 2.0" with info about company_id/realmId.
Thanks:)

**Comment by mikesafdieh** [comment]
I am having this issue as well. My views are as follows:

```
def qb_authorize(request):
    user = request.user
    if user.is_superuser:
        if request.GET.get('action', None) == 'Authorize':

            QB_CONFIG = settings.CONFIG['quickbooks']
            session_manager = Oauth2SessionManager(
                client_id=QB_CONFIG['client_id'],
                client_secret=QB_CONFIG['client_secret'],
                base_url=QB_CONFIG['base_url'],
                sandbox=QB_CONFIG['sandbox'],
            )

            callback_url = QB_CONFIG['base_url'] + '/accounts/qb-authorize-callback/'  # Quickbooks will send the response to this url
            authorize_url = session_manager.get_authorize_url(callback_url)            

            return redirect(authorize_url)
        else:
            return render(request, "accounts/qb-authorize.html")
    else:
        return redirect('/')


def qb_authorize_callback(request):
    QB_CONFIG = settings.CONFIG['quickbooks']

    try:
        oauth2_obj = OAuth2Store.objects.get(client_id=QB_CONFIG['client_id'])
    except ObjectDoesNotExist:
        oauth2_obj = OAuth2Store.objects.create(client_id=QB_CONFIG['client_id'])

    session_manager = Oauth2SessionManager(
        client_id=oauth2_obj.client_id,
        client_secret=QB_CONFIG['client_secret'],
        base_url=QB_CONFIG['base_url'],
        sandbox=QB_CONFIG['sandbox'],
    )
    session_manager.company_id = request.GET.get('realmId')
    # import ipdb; ipdb.set_trace()
    session_manager.get_access_tokens(request.GET['code'])
    access_token = session_manager.access_token

    oauth2_obj.access_token = access_token
    oauth2_obj.client_secret = QB_CONFIG['client_secret']
    oauth2_obj.realm_id = request.GET.get('realmId', None)
    oauth2_obj.save()

    return render(request, "accounts/qb-complete.html", {'complete': True})
```

What exactly is company_id? It doesn't seem to be a property of session_manager. Also, should I not be creating a new session_manager in the callback view? If so, how would I go about passing a session_manager between the 2 views? 

Additionally, is it necessary for me to add state? It's not mentioned at all in the README example.

**Comment by deoresheetal** [comment]
@mikesafdieh You can create new session_manager object in callback view, about company_id, its realm_id that your callback returns, you can retrieve it by
`company_id = request.get("realmId")`
  `auth_code = request.get("code")`
now after creating your session_manager object in callback assign this company_id to it,
`session_manager.company_id = company_id`
`session_manager.get_access_tokens(auth_code)`

also, its not necessary to add state, I added it identify for which request I am getting the callback so that I can map the tokens.
Hope this helps
