### ISSUE TITLE
Cannot create an invoice

### ISSUE THREAD

**Issue by maicat11** [sidecars/python-quickbooks#96]
I have no problem connecting and getting data from an invoice, but I have been doing everything I can think of to create and POST a new invoice to my QBO sandbox.  My goal is to post many invoices without having to do it manually.  

Here is what I have tried:

From Intuit developer site minimum attribute requirements and types found here for creating an invoice: https://developer.intuit.com/docs/api/accounting/invoice

invoice_data = {attributes json data in here guided from Intuit dev site above}

invoice = Invoice()
invoice.from_json(invoice_data)
invoice.save(qb=client)

I received this as an error: 
QuickbooksException: Required param missing, need to supply the required value for the API
(It would be great to know which parameters I was missing)

So I decided to put ALL possible parameters since I don't know which is missing and I followed the data type from above link, then I started to receive this error message instead: 
TypeError: string indices must be integers

I have tried correcting values by changing string values into integers and still receive the same error.  
I am now stuck. 

Can anyone out there please help in this effort?  

Thank you!!!
Mailei

**Comment by ej2** [comment]
The sample data given on the invoice docs may not be complete. Try taking your json data and creating an invoice via the QBO API Explorer: https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice

**Comment by maicat11** [comment]
Thanks for the response, but I was trying to create roughly 5000 invoices not just one.  I got it figured out over the weekend in a very 'hackerish' way, but it works for what I am doing.  

Thanks,
Mailei
