### ISSUE TITLE
refresh_token usage

### ISSUE THREAD

**Issue by Brian-CLO** [sidecars/python-quickbooks#97]
I'm following this logic from the Intuit developer pages. 

https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app

Specifically, this section where it says it's best not to store the access_token. 

Token storage best practices

In persistent storage, save the OAuth refresh_token and realmId, associating them with the user who is currently authorizing access.  Be sure to encrypt the refresh_token before saving it to persistent storage. Then, decrypt the it and store it in volatile memory when you need to use it to refresh the access_token.

The access_token is supplied in the authorization header for every call to a QuickBooks API resource. Store it in volatile memory so it is readily available during contexts in which calls to API resources are made. Examples of these contexts include:

The life of a signed-in user session.
The life of a connection.

My Question: 
Is there an existing way to set up a session manager without an access token, but with the remaining values and request a new access_token using the refresh token?

**Comment by bendavis78** [comment]
@Brian-CLO Did you find a solution to this?

**Comment by E-G-C** [comment]
It has been a while... do you guys figure this out or still need some help with it?

**Comment by ej2** [comment]
No longer relevant since OAuth Session Manager has been removed.
