### ISSUE TITLE
Readme for "Manually connecting with OAuth version 2.0" references undeclared variable

### ISSUE THREAD

**Issue by danielvinson** [sidecars/python-quickbooks#98]
In this code:

```
from quickbooks import Oauth2SessionManager

session_manager = Oauth2SessionManager(
    sandbox=True,
    client_id=QUICKBOOKS_CLIENT_ID,
    client_secret=QUICKBOOKS_CLIENT_SECRET,
    base_url='http://localhost:8000',
)

callback_url = 'http://localhost:8000'  # Quickbooks will send the response to this url
authorize_url = client.get_authorize_url(callback_url)
request_token = client.request_token
request_token_secret = client.request_token_secret
```

What does "client" reference?  Nothing seems to specify it, and when I tried the obvious answer of running that exact code using a client = QuickBooks(...) from another example it didn't work.  

I'm guessing that this code is just missing a few lines?

**Comment by vjimw** [comment]
I think client should just be session_manager in that example. If I swap them, it works for me and I can get the authorize URL through session_manager.get_authorize_url(callback_url).

**Comment by vaibhavM55** [comment]
if you add session_manager for authorize_url(), it works.
But neither the client nor the session_manager work for request_token and request_token_secret
Can anyone help with the authorization part pls, how is it done?

**Comment by benbogart** [comment]
It would be helpful to have working examples in the readme or elsewhere.  I too can't get past authorization using this module.

**Comment by ej2** [comment]
Sorry about that... the readme has been updated.

**Comment by benbogart** [comment]
Almost.  We get one line further through the example then I get:
AttributeError: 'Oauth2SessionManager' object has no attribute 'request_token'

**Comment by ej2** [comment]
Oauth2SessionManager does not have a request_token or request_token_secret (they are only used on OAuth1). So you can remove both of the following lines:

`request_token = client.request_token`
`request_token_secret = client.request_token_secret`

**Comment by benbogart** [comment]
I realized that after I posted.  Sorry, and thanks again.

**Comment by benbogart** [comment]
I still can't get the code in the readme to generate an auth_code.

I am able to generate the auth_code with the cli so the problem is me, but I'm stuck.

The line:
requests.post(self.access_token_url, data=payload, headers=headers)
OAuth2SessionManager.get_access_tokens returns:
<Response [400]>
{"error":"invalid_grant"}

Here are the views I am using with Django which are failing me.  Any insight would be helpful.


```
from django.http import HttpResponse

from quickbooks import Oauth2SessionManager

session_manager = Oauth2SessionManager(
    sandbox=True,
    client_id='MY_ID_HERE',
    client_secret='MY_SECRET_HERE',
    base_url='http://localhost:8000/qb/',
)

def index(request):
    callback_url = 'http://localhost:8000/qb/callback'  # Quickbooks will send the response to this url
    authorize_url = session_manager.get_authorize_url(callback_url)
    return HttpResponse("Hello, world. You're at the qb index. - The Auth url is " + authorize_url)


def callback(request):
    session_manager.get_access_tokens(request.GET['code'])
    access_token = session_manager.access_token

    return HttpResponse("Your access token is: " + access_token)
```
