### ISSUE TITLE
OAuth2 and refresh tokens

### ISSUE THREAD

**Issue by kamil-i2a** [sidecars/python-quickbooks#99]
@ej2 

Does python-quickbooks support refreshing the `access_token`? Neither README nor the code mention anything like that.

For now, OAuth2 example from README work for 1 hour, then `access_token` invalidates. Could you please update README with an example on how to refresh access?

**Comment by Brian-CLO** [comment]
I ended up adding this functionality myself. It was pretty straightforward. I'm happy to contribute it back if anyone is interested.

**Comment by cstarner** [comment]
Please do, it would be greatly appreciated.

**Comment by stolbejj77** [comment]
@Brian-CLO did you happen to contribute the refresh functionality somewhere?  I looked through your fork and was unable to spot it.

**Comment by JohnBloom** [comment]
Rather than update the repo and try and get a pull request in I made a method that given an Oauth2 session manager and refresh token will refresh the auth. Here is the method:
```
def get_new_auth_token(self, session_manager, refresh_token):
        headers = {
            'Accept': 'application/json',
            'content-type': 'application/x-www-form-urlencoded',
            'Authorization': session_manager.get_auth_header()
        }

        payload = {
            'refresh_token': refresh_token,
            'grant_type': 'refresh_token'
        }

        r = requests.post(session_manager.access_token_url, data=payload, headers=headers)
        if r.status_code != 200:
            return r.text

        bearer_raw = json.loads(r.text)

        session_manager.x_refresh_token_expires_in = bearer_raw['x_refresh_token_expires_in']
        session_manager.access_token = bearer_raw['access_token']
        session_manager.token_type = bearer_raw['token_type']
        session_manager.refresh_token = bearer_raw['refresh_token']
        session_manager.expires_in = bearer_raw['expires_in']
```

**Comment by johnnydisco** [comment]
Please can someone explain how to use this refresh function or how to refresh the token in general.  I'm all good up to the point of needing to refresh but cannot for the life of me figure out how to refresh without rewriting a load of code..  Surely someone has already implemented this?

Thanks for all your help.

Cheers,
Johnny

**Comment by JohnBloom** [comment]
What in particular are you having trouble with? The function takes a session and the token, it refreshes the token and then updates the session. There isnt that much to it.

**Comment by pembo13** [comment]
@JohnBloom  not sure how active this project is, but would be good to see your code merged in.

**Comment by ej2** [comment]
This is an active project. Sorry I haven't got to the PRs, I have been swamped at work the last couple of months. Will try to carve out time soon to merge them.

**Comment by dsclough** [comment]
@JohnBloom trying to make use of your method and the requests.post line is always returning a 401. I'm able to save things to quickbooks with the same session manager just fine, any idea what could be the issue?

inputs to the function below:

access_token_url: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
headers: {'content-type': 'application/x-www-form-urlencoded', 'Accept': 'application/json', 'Authorization': 'Basic somelongtoken'}
payload: {'refresh_token': 'shortertoken', 'grant_type': 'refresh_token'}
<Response [401]>

**Comment by bendavis78** [comment]
Does `client.reconnect_account` work with Oauth2?

**Comment by ej2** [comment]
Refresh token has been added to the Oauth2 session manager. See the readme for details.
